Repository CentOS-PaaS-SIG/linchpin, pull requests merged in 2018-10, with the labels that each got.

#720 Updated pinfile path to use workspace when mentioned
  linchpin/cli/__init__.py
Labels: bug, cli

#725 Update flags ordering and add metavars
  linchpin/shell/__init__.py
Labels: bug, cli

#729 Remove duplicate task in dummy provider
  linchpin/provision/roles/dummy/tasks/provision_resource_group.yml
Labels: bug, dummy

#730 Linchpin container release process - rework
  config/Dockerfiles/JenkinsfileBuilder
  config/Dockerfiles/JenkinsfileContainerBuild
  config/Dockerfiles/Makefile
  config/Dockerfiles/linchpin/Dockerfile
  config/Dockerfiles/linchpin/Makefile
  config/Dockerfiles/linchpin/bin/run-linchpin
  config/Dockerfiles/linchpin/test/run
  config/s2i/create-containers.sh
  config/s2i/jenkins/buildah-buildconfig-template.yaml
  config/s2i/jenkins/buildah/Dockerfile
  docs/source/examples/workspaces/dummy/PinFile
Labels: cd, containers

#740 Updated configparser version from ancient to 3.5
  requirements.txt
Labels: bug, inventory

#750 Make linchpin validate stop printing [ERROR] on success
  linchpin/__init__.py
  linchpin/shell/__init__.py
Labels: bug

#752 Enables multi-file ansible hook in linchpin
  config/Dockerfiles/tests.d/dummy/04_dummy-hook-flags
  config/Dockerfiles/tests.d/dummy/05-dummy-multi-file-hook
  docs/source/examples/workspaces/dummy-multi-file-hook/PinFile
  docs/source/examples/workspaces/dummy-multi-file-hook/credentials/.empty
  docs/source/examples/workspaces/dummy-multi-file-hook/hooks/.empty
  docs/source/examples/workspaces/dummy-multi-file-hook/hooks/ansible/ex_hook/ex1.yaml
  docs/source/examples/workspaces/dummy-multi-file-hook/hooks/ansible/ex_hook/ex2.yaml
  docs/source/examples/workspaces/dummy-multi-file-hook/inventories/.empty
  docs/source/examples/workspaces/dummy-multi-file-hook/layouts/dummy-layout.yml
  docs/source/examples/workspaces/dummy-multi-file-hook/localhost
  docs/source/examples/workspaces/dummy-multi-file-hook/topologies/.empty
  docs/source/examples/workspaces/dummy-multi-file-hook/topologies/dummy-topology.yml
  linchpin/hooks/__init__.py
  linchpin/hooks/action_managers/ansible_action_manager.py
Labels: bug

#760 Fix Typos in Getting Started Docs
  docs/source/examples/workspaces/dummy/PinFile
  docs/source/simple_pinfile.rst
  docs/source/simple_up.rst
  docs/source/simple_workspace.rst
Labels: documentation
