Repository CentOS-PaaS-SIG/linchpin, pull requests merged in 2018-06, with the labels that each got.

#587 Rework CI tests to allow for ignoring, provider, and more
  .gitignore
  config/Dockerfiles/Jenkinsfile
  config/Dockerfiles/JenkinsfileContainer
  config/Dockerfiles/Makefile
  config/Dockerfiles/linchpin-test.sh
  config/Dockerfiles/linchpin-tests.sh
  config/Dockerfiles/run_tests.sh
  config/Dockerfiles/tests.d/aws/.empty
  config/Dockerfiles/tests.d/beaker/.empty
  config/Dockerfiles/tests.d/dummy/01_dummy-template-data
  config/Dockerfiles/tests.d/dummy/02_dummy-template-data-file
  config/Dockerfiles/tests.d/general/01_general
  config/Dockerfiles/tests.d/inventory/01_template_inventory
  config/Dockerfiles/tests.d/libvirt/.empty
  config/Dockerfiles/tests.d/openstack/02_os-server-template
  config/Dockerfiles/tests.d/openstack/03_os-server-template-file
  config/Dockerfiles/tests.d/openstack/04_os-sg-new
  config/Dockerfiles/tests.d/openstack/05_os-vol-new
  config/README.rst
  docs/source/examples/workspace/PinFile.aws.yml
  docs/source/examples/workspace/PinFile.beaker.yml
  docs/source/examples/workspace/PinFile.complex.yml
  docs/source/examples/workspace/PinFile.duffy.yml
  docs/source/examples/workspace/PinFile.dummy.yml
  docs/source/examples/workspace/PinFile.libvirt.yml
  docs/source/examples/workspace/PinFile.openstack.yml
  docs/source/examples/workspace/PinFile.template-inventory.yml
  docs/source/examples/workspace/layouts/libvirt-new.yml
  docs/source/examples/workspace/layouts/template-inventory.yml
  docs/source/examples/workspace/template-data/template-inventory.yml
  docs/source/examples/workspace/topologies/dummy-new.yml
  docs/source/examples/workspace/topologies/libvirt-network.yml
  docs/source/examples/workspace/topologies/libvirt-template-inventory.yml
  docs/source/examples/workspace/topologies/os-server-new.yml
  docs/source/examples/workspace/topologies/os-vol-new.yml
  linchpin/cli/__init__.py
  linchpin/provision/roles/duffy/tasks/main.yml
  linchpin/provision/roles/duffy/tasks/teardown_res_defs.yml
  linchpin/provision/roles/duffy/tasks/teardown_resource_group.yml
  src/org/centos/pipeline/LinchpinPipelineUtils.groovy
  vars/linchpinPipelineUtils.groovy
Labels: ci, testing, testing_required

#586 github_issue_547: Basic support for remote libvirt hypervisors
  linchpin/provision/roles/libvirt/tasks/copy_image_src_remote.yml
  linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
  linchpin/provision/roles/libvirt/tasks/provision_res_defs.yml
  linchpin/provision/roles/libvirt/tasks/teardown_libvirt_node.yml
Labels: testing_required

#603 Minor docs fixes
  docs/source/community.rst
  docs/source/conf.py
  docs/source/developer_info.rst
  docs/source/gs/pinfile.rst
  docs/source/includes/footer.rst
  docs/source/includes/pinfile.rst
  docs/source/index.rst
  docs/source/intro_config.rst
Labels: documentation

#600 A more specific MANIFEST.in and setup.py
  MANIFEST.in
  docs/source/examples/workspace/resources/.empty
  linchpin/version.py
  setup.py
Labels: cd, release

#594 Jenkins release job
  config/Dockerfiles/JenkinsfileRelease
  config/Dockerfiles/linchpin-pip-install.sh
  config/s2i/jenkins/master/configuration/jobs/cd-linchpin-release/config.xml
  config/s2i/jenkins/slave/Dockerfile
  docs/source/examples/workspace/topologies/os-server-new.yml
  linchpin/version.py
Labels: cd

#608 ks_meta in recipesets is valid schema.
  linchpin/provision/roles/beaker/files/schema.json
Labels: beaker

#609 Run one resource at a time
  config/Dockerfiles/tests.d/combined/01_beaker_openstack
  docs/source/examples/workspace/PinFile.beaker-openstack.yml
  linchpin/__init__.py
  linchpin/provision/roles/beaker/files/schema.json
  linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
Labels: api, bug
