Repository CentOS-PaaS-SIG/linchpin, pull requests merged in 2018-11, with the labels that each got.

#787 Issue #785: os_keypair is failing when trying to generate an Openstack keypair.
  linchpin/provision/roles/openstack/tasks/provision_os_keypair.yml
Labels: bug, openstack

#788 Fail faster when resource provisioning fails + switch off ignore errors in beaker
  linchpin/__init__.py
  linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
Labels: api, beaker, bug

#742 [POC]: Introducing Dummy domain as a parameter to generate fake inventories
  linchpin/provision/library/dummy.py
  linchpin/provision/roles/dummy/files/schema.json
  linchpin/provision/roles/dummy/tasks/provision_res_defs.yml
Labels: POC

#759 Linchpin setup and Adding error handling messages beaker and libvirt
  docs/source/installation.rst
  linchpin/__init__.py
  linchpin/cli/__init__.py
  linchpin/provision/ask_sudo_setup.yml
  linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
  linchpin/provision/roles/dependencies/tasks/beaker_deps.yml
  linchpin/provision/roles/dependencies/tasks/docs_deps.yml
  linchpin/provision/roles/dependencies/tasks/libvirt_deps.yml
  linchpin/provision/roles/dependencies/tasks/main.yml
  linchpin/provision/roles/dependencies/tasks/setup_dnf_deps.yml
  linchpin/provision/roles/dependencies/tasks/setup_selinux_deps.yml
  linchpin/provision/roles/dependencies/tasks/test_deps.yml
  linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
  linchpin/provision/roles/libvirt/tasks/virt_customize.yml
  linchpin/provision/setup.yml
  linchpin/shell/__init__.py
Labels: cli

#804 Pre release linchpin 1.6.5
  config/Dockerfiles/linchpin-tests.sh
  linchpin/version.py
Labels: release

#808 Added wait timeout parameter to aws_ec2 module
  linchpin/provision/roles/aws/files/schema.json
  linchpin/provision/roles/aws/tasks/provision_aws_ec2.yml
Labels: rfe

#806 Issue #803: When running os-keypair, no local keyfile is generated at…
  linchpin/provision/roles/openstack/tasks/provision_os_keypair.yml
Labels: bug
