Repository CentOS-PaaS-SIG/linchpin, pull requests merged in 2019-09, with the labels that each got.

#1312 Fix Openstack Network managment
  docs/source/examples/workspaces/openstack-net/PinFile
  docs/source/examples/workspaces/openstack-net/README.md
  docs/source/examples/workspaces/openstack-net/linchpin.conf
  linchpin/provision/roles/openstack/files/schema.json
  linchpin/provision/roles/openstack/tasks/main.yml
  linchpin/provision/roles/openstack/tasks/provision_os_network.yml
  linchpin/provision/roles/openstack/tasks/provision_os_router.yml
  linchpin/provision/roles/openstack/tasks/provision_os_subnet.yml
  linchpin/provision/roles/openstack/tasks/teardown_os_heat.yml
  linchpin/provision/roles/openstack/tasks/teardown_os_keypair.yml
  linchpin/provision/roles/openstack/tasks/teardown_os_network.yml
  linchpin/provision/roles/openstack/tasks/teardown_os_object.yml
  linchpin/provision/roles/openstack/tasks/teardown_os_router.yml
  linchpin/provision/roles/openstack/tasks/teardown_os_server.yml
  linchpin/provision/roles/openstack/tasks/teardown_os_sg.yml
  linchpin/provision/roles/openstack/tasks/teardown_os_subnet.yml
  linchpin/provision/roles/openstack/tasks/teardown_os_volume.yml
  linchpin/provision/roles/openstack/tasks/teardown_resource_group.yml
Labels: bug

#1336 Make container image changes necessary to run openstack cleanup nightly
  config/Dockerfiles/centos7/Dockerfile
Labels: ci

#1343 Move python2-dnf dependency to pip
  linchpin/provision/roles/dependencies/tasks/libvirt_deps.yml
Labels: bug

#1347 Update aws ec2 examples to reflect changes in account
  docs/source/examples/workspaces/aws-simple/PinFile
  docs/source/examples/workspaces/aws/PinFile
  docs/source/examples/workspaces/dummy-aws/PinFile.dummy-aws.yml
Labels: documentation, testing

#1287 Add minimal tests to libvirt and streamline defaults
  config/Dockerfiles/tests.d/aws/08_aws_ec2_vpc_nat_gateway
  config/Dockerfiles/tests.d/general/01_minimal
  docs/source/examples/workspaces/libvirt/PinFile
  linchpin/provision/roles/libvirt/files/defaults.yml
  linchpin/provision/roles/libvirt/files/schema.json
  linchpin/provision/roles/libvirt/tasks/copy_image_src_local.yml
  linchpin/provision/roles/libvirt/tasks/copy_image_src_remote.yml
  linchpin/provision/roles/libvirt/tasks/provision_libvirt_network.yml
  linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
  linchpin/provision/roles/libvirt/tasks/provision_res_defs.yml
  linchpin/provision/roles/libvirt/tasks/provision_resource_group.yml
  linchpin/provision/roles/libvirt/tasks/teardown_libvirt_network.yml
  linchpin/provision/roles/libvirt/tasks/teardown_libvirt_node.yml
  linchpin/provision/roles/libvirt/tasks/virt_customize.yml
  linchpin/provision/roles/libvirt/templates/libvirt_network.xml.j2
  linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
Labels: bug

#1350 Python3 fix for --use-shell flag
  linchpin/ansible_runner.py
Labels: ansible, ansible_runner, bug, python3x, use-shell

#1352 Fix syntax errors on linchpin setup.yml
  linchpin/provision/roles/dependencies/tasks/main.yml
Labels: 1
