Repository CentOS-PaaS-SIG/linchpin, pull requests merged in 2019-06, with the labels that each got.

#1155 Remove inventory_gen folder from roles
  linchpin/provision/roles/inventory_gen/handlers/main.yml
  linchpin/provision/roles/inventory_gen/tasks/main.yml
  linchpin/provision/roles/inventory_gen/templates/aws_inventory_formatter.j2
  linchpin/provision/roles/inventory_gen/templates/beaker_inventory_formatter.j2
  linchpin/provision/roles/inventory_gen/templates/duffy_inventory_formatter.j2
  linchpin/provision/roles/inventory_gen/templates/gcloud_inventory_formatter.j2
  linchpin/provision/roles/inventory_gen/templates/generic_inventory_formatter.j2
  linchpin/provision/roles/inventory_gen/templates/libvirt_inventory_formatter.j2
  linchpin/provision/roles/inventory_gen/templates/openstack_inventory_formatter.j2
Labels: cleanup

#1160 Fixes for OpenStack 'additional_volumes'
  linchpin/FilterUtils/FilterUtils.py
  linchpin/provision/roles/openstack/files/schema.json
  linchpin/provision/roles/openstack/tasks/provision_os_server.yml
  linchpin/tests/InventoryFilters/test_FilterPlugins_pass.py
Labels: bug

#1150 Enable openstack-cleanup in integration tests
  config/Dockerfiles/tests.d/general/01_general
Labels: ci
