Repository CentOS-PaaS-SIG/linchpin, pull requests merged in 2019-07, with the labels that each got.

#1169 Introducing preview version of linchpin api V2 for 1.7.6
  docs/source/conf.py
  docs/source/examples/workspaces/dummy-creds-vault/linchpin.conf
  docs/source/getting_started.rst
  docs/source/libbase.rst
  docs/source/linchpin_api.rst
  linchpin/__init__.py
  linchpin/api/__init__.py
  linchpin/context.py
  linchpin/linchpin.constants
  linchpin/tests/mockdata/api_workspace/PinFile
  linchpin/tests/test_init_pass.py
  setup.py
Labels: api

#1191 remove duplicate requirements.txt
  requirements.txt
Labels: bug

#1192 release 1.7.6.1
  linchpin/version.py
Labels: release

#1184 Fix bugs causing unit tests to fail in python 3
  .travis.yml
  linchpin/InventoryFilters/AWSInventory.py
  linchpin/InventoryFilters/BeakerInventory.py
  linchpin/InventoryFilters/DockerInventory.py
  linchpin/InventoryFilters/DuffyInventory.py
  linchpin/InventoryFilters/DummyInventory.py
  linchpin/InventoryFilters/GCloudInventory.py
  linchpin/InventoryFilters/LibvirtInventory.py
  linchpin/InventoryFilters/OpenstackInventory.py
  linchpin/InventoryFilters/OvirtInventory.py
  linchpin/InventoryFilters/VMwareInventory.py
  linchpin/tests/InventoryFilters/test_GenericInventory_pass.py
  linchpin/tests/mockdata/complex-inventory/correct-inventory
Labels: testing

#1175 Add option to disable uhash for specific targets via the command line
  .travis.yml
  docs/source/advanced/layouts.rst
  docs/source/includes/provisioning.rst
  linchpin/__init__.py
  linchpin/ansible_runner.py
  linchpin/provision/roles/dummy/tasks/provision_res_defs.yml
  linchpin/provision/roles/dummy/tasks/teardown_res_defs.yml
  linchpin/provision/roles/gather_resources/tasks/main.yml
  linchpin/provision/roles/gcloud/tasks/provision_res_defs.yml
  linchpin/provision/roles/libvirt/tasks/provision_res_defs.yml
  linchpin/provision/roles/nummy/tasks/provision_res_defs.yml
  linchpin/provision/roles/nummy/tasks/teardown_res_defs.yml
  linchpin/provision/roles/openstack/tasks/provision_res_defs.yml
  linchpin/provision/roles/ovirt/tasks/provision_res_defs.yml
  linchpin/shell/__init__.py
  linchpin/tests/test_init_pass.py
  playbooks/tests/unit_tests.yml
Labels: rfe
