Repository CentOS-PaaS-SIG/linchpin, pull requests merged in 2019-04, with the labels that each got.

#1052 Fix indentation in examples of tutorials
  docs/source/tutorials/aws.rst
  docs/source/tutorials/beaker.rst
  docs/source/tutorials/templates/layout.rst
Labels: bug, documentation

#695 Implementation of builtin_hooks: check_ssh, port_up, ping
  MANIFEST.in
  config/Dockerfiles/tests.d/general/01_general
  config/Dockerfiles/tests.d/inventory/01_template_inventory
  config/Dockerfiles/tests.d/libvirt/05_libvirt-builtins
  docs/source/examples/workspaces/libvirt-global-hooks/PinFile
  docs/source/examples/workspaces/libvirt-global-hooks/README.rst
  docs/source/examples/workspaces/libvirt-global-hooks/custom.xml
  linchpin/hooks/__init__.py
  linchpin/hooks/built_ins/__init__.py
  linchpin/hooks/built_ins/check_ssh/__init__.py
  linchpin/hooks/built_ins/check_ssh/check_ssh.yaml
  linchpin/hooks/built_ins/ping/__init__.py
  linchpin/hooks/built_ins/ping/ping.yaml
  linchpin/hooks/built_ins/port_up/__init__.py
  linchpin/hooks/built_ins/port_up/port_up.yaml
Labels: hooks

#1055 Updated resource_names with prefix ci-lp-cp-
  docs/source/examples/workspaces/openstack/PinFile
  docs/source/examples/workspaces/openstack/topologies/os-vol-new.yml
Labels: ci, testing

#1068 Fix validation error on destroy when use_rundb_for_actions is enabled
  linchpin/validator/__init__.py
Labels: bug

#1065 Automate the updating of github release notes
  config/Dockerfiles/JenkinsfileRelease
  config/Dockerfiles/centos7/Dockerfile
  config/Dockerfiles/fedora28/Dockerfile
  config/Dockerfiles/fedora29/Dockerfile
  config/Dockerfiles/release-notes.py
Labels: ci

#1069 Add credentials information to GCloud documentation
  docs/source/credentials/gcloud.rst
  docs/source/gcloud.rst
Labels: documentation

#1075 Documentation: Add disk_cache parameter to topology schema
  docs/source/libvirt.rst
Labels: documentation

#671 Replace os_hot_stack module with os_stack upstream ansible module
  config/Dockerfiles/tests.d/openstack/06_os-heat
  docs/source/examples/workspaces/openstack-heat/PinFile
  docs/source/examples/workspaces/openstack-heat/os_stack.yml
  linchpin/provision/library/os_hot_stack.py
  linchpin/provision/roles/openstack/files/schema.json
  linchpin/provision/roles/openstack/tasks/provision_os_heat.yml
Labels: openstack

#1084 VMware guest support
  config/Dockerfiles/tests.d/general/01_general
  docs/source/credentials/vmware.rst
  docs/source/examples/workspace/topologies/vmware.yml
  docs/source/examples/workspaces/vmware/PinFile
  docs/source/examples/workspaces/vmware/README.md
  docs/source/examples/workspaces/vmware/linchpin.conf
  docs/source/examples/workspaces/vmware/localhost
  docs/source/examples/workspaces/vmware/vmware.key
  docs/source/vmware.rst
  linchpin/InventoryFilters/InventoryProviders.py
  linchpin/InventoryFilters/VMwareInventory.py
  linchpin/provision/README.rst
  linchpin/provision/roles/gather_resources/tasks/main.yml
  linchpin/provision/roles/gather_resources/tasks/update_vmware_guest_outputs.yml
  linchpin/provision/roles/gather_resources/tasks/wait_on_vmware_guest.yml
  linchpin/provision/roles/vmware/files/schema.json
  linchpin/provision/roles/vmware/tasks/main.yml
  linchpin/provision/roles/vmware/tasks/provision_res_defs.yml
  linchpin/provision/roles/vmware/tasks/provision_resource_group.yml
  linchpin/provision/roles/vmware/tasks/provision_vmware_guest.yml
  linchpin/provision/roles/vmware/vars/ex_vmware_creds.yml
  linchpin/provision/site.yml
  linchpin/provision/vmware.yml
  linchpin/tests/InventoryFilters/test_GenericInventory_pass.py
  linchpin/tests/InventoryFilters/test_InventoryProviders_pass.py
  linchpin/tests/InventoryFilters/test_VMwareInventory_pass.py
  linchpin/tests/mockdata/general-inventory/PinFile
  linchpin/tests/mockdata/general-inventory/linchpin.benchmark
  setup.py
Labels: community, vmware

#1090 Fix errors in unit tests
  linchpin/tests/InventoryFilters/test_CFGInventoryFormatter_pass.py
  linchpin/tests/InventoryFilters/test_InventoryFilter_pass.py
  linchpin/tests/InventoryFilters/test_JSONInventoryFormatter_pass.py
  linchpin/tests/mockdata/complex-inventory/correct-inventory
Labels: bug

#1096 Fix the deprecation Warning in tinydb
  linchpin/rundb/tinyrundb.py
Labels: bug

#1099 Add support for libvirt root disk type
  docs/source/libvirt.rst
  linchpin/provision/roles/libvirt/files/schema.json
  linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
  linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
Labels: libvirt, rfe

#1060 Release v1.7.4
  linchpin/version.py
Labels: release
