Repository CentOS-PaaS-SIG/linchpin, pull requests merged in 2020-02, with the labels that each got.

#1608 Fix bug preventing topology outputs from multiple sources from being collected
  linchpin/provision/roles/gather_resources/tasks/main.yml
Labels: bug

#1610 Add file permissions to keyfiles created
  linchpin/FilterUtils/FilterUtils.py
Labels: 1, bug, filter_plugins

#1597 Fix remote provisioning of libvirt accross environments (except virtualenvs)
  docs/source/examples/workspaces/libvirt/custom.xml
  linchpin/provision/roles/libvirt/files/schema.json
  linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
Labels: bug

#1620 Fix bug in which 'cloud_config_used' is undefined
  linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
Labels: bug

#1625 Flake8 fixes to make github linting actions to succeed
  linchpin/FilterUtils/FilterUtils.py
  linchpin/__init__.py
  linchpin/provision/action_plugins/ec2.py
  linchpin/provision/action_plugins/libvirt_network.py
  linchpin/provision/action_plugins/libvirt_node.py
  linchpin/provision/action_plugins/libvirt_storage.py
  linchpin/provision/filter_plugins/cpu_to_int.py
  linchpin/provision/filter_plugins/memory_to_int.py
  setup.py
Labels: 1, flake8

#1643 Disable unit tests in Jenkins
  config/Dockerfiles/JenkinsfileGHPRTrigger
  config/Dockerfiles/JenkinsfileUnitTests
Labels: ci
